/**:
  ros__parameters:
    JoyTopicInterface:
      feedback_mode: "PositionFeedback" 

      gain:
        horizontal: 0.3
        rotational: 0.3

      # topic_name: "/cmd_joy"
      # frame_id: "user_frame"

      diable_pose_feedback: true