/**:
  ros__parameters:
    JoyTopicInterface:
      feedback_mode: "NoFeedback" 

      gain:
        horizontal: 0.2
        rotational: 0.3

      topic_name: "/spacenav/joy"
      frame_id: "user_frame"

      diable_pose_feedback: true