/**:
  ros__parameters:
    PoseTopicInterface:
      feedback_mode: "PositionFeedback" 

      topic_name: "/cmd_pose"
      frame_id: "user_frame"

      diable_pose_feedback: false # if this true, the robot does not move to the target pose