/**:
  ros__parameters:
    XrBodyInterface:
      feedback_mode: "PositionFeedback" 

      topic_name: "/body_state"
      frame_id: "user_frame"

/**:
  ros__parameters:
    fr3_right/body_part: "LEFT_HAND"
    fr3_left/body_part: "RIGHT_HAND"