/**:
  ros__parameters:
    XrBodyInterface:
      feedback_mode: "HybridFeedback" 

      topic_name: "/body_state"
      frame_id: "user_frame"

/**:
  ros__parameters:
    torobo2_right/body_part: "RIGHT_HAND"
    torobo2_left/body_part: "LEFT_HAND"