/**:
  ros__parameters:
    so101:
      chain_start: "/base_link" # base frame of commands
      chain_end: "/gripper_link" # target eff frame

      publisher: "JointState" # "Position" or "Velocity" or "Trajectory" or "TrajectoryAction"
      topic_namespace: "so101_follower"

      initIKAngle: [0.0, 0.0, 0.0, 0.0, 0.0] # size of this should be equal to DoF

      # initial_pose_frame: test # default frame is same as chain_start
      initial_pose: [0.0, -0.28, 0.23, 0.0, 0.0, 0.0] # [x, y, z, roll, pitch, yaw]