/**:
  ros__parameters:
    gen3_lite:
      chain_start: "base_link" # base frame of commands
      chain_end: "tool_frame" # target eff frame

      publisher: "Trajectory" # "Position" or "Velocity" or "Trajectory" or "TrajectoryAction"
      topic_namespace: "joint_trajectory_controller"

      initIKAngle: [1.0, -0.36, 1.08, -1.57, -1.69, 0.0] # size of this should be equal to DoF

      # initial_pose_frame: test # default frame is same as chain_start
      initial_pose: [0.35, 0.0, 0.3, 0.0, 3.141592, 0.0] # [x, y, z, roll, pitch, yaw]