/**:
  ros__parameters:
    ur5:
      chain_start: "world" # base frame of commands
      chain_end: "tool0" # target eff frame

      publisher: "Velocity" # "Position" or "Velocity" or "Trajectory" or "TrajectoryAction"
      topic_namespace: "forward_velocity_controller"

      initIKAngle: [3.5, -1.0, 1.5, -2.1, 0.6, 0.2] # size of this should be equal to DoF

      # initial_pose_frame: test # default frame is same as chain_start
      initial_pose: [0.55, 0.0, 0.9, 3.141592, 0.0, 0.0] # [x, y, z, roll, pitch, yaw]