/**:
  ros__parameters:
    root_frame: "world" # IK calculation base frame (for multi-follower)
    controller: "Velocity" # "Position" or "Velocity"

    solver: "MyIK"

    self_collision_avoidance: true

    control_freq: 500.0

    follower:
      hw: ["ur5e"] # robot config name, which needs to be defined in hw_config.yaml
      ns: # robot namespaces for each robot, which should be unique among all robots. ("") means the robot has no namespace
        ur5e: [""]

    # Type of solving IK. "Concatenated" mode solve IK for all robots at once. "Order" mode solve IK for each robot in order. "Parallel" mode solve IK for all robots in multi thread.
    # When you operate single robot, "Concatenated" mode is equivalent to "Order" mode.
    IK_mode: "Concatenated" # "Order" # "Parallel" #

    priority: "Manual" #"Automation" #  (for multi-follower)
    MF_mode: "Individual"  #  (for multi-follower)
